#!/usr/bin/env python3

import os
import sys
import nltk  # http://www.nltk.org/
from nltk.tokenize import TweetTokenizer # http://www.nltk.org/api/nltk.tokenize.html
from analyzer import Analyzer
from termcolor import colored
import helpers 

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    #CREATE TWEETS
    tweets = helpers.get_user_timeline(sys.argv[1], 100)
    
    #anlayse tweets
    
    negtweet = 0
    postweet = 0
    neutweet = 0
    
    for tweet in tweets:
        score = 0
        tweetscore = analyzer.analyze(tweet)
        if tweetscore > 0:
            postweet += 1
            print(colored("{} {}".format(tweetscore, tweet), "green"))
        elif tweetscore < 0:
            negtweet += 1
            print(colored("{} {}".format(tweetscore, tweet), "red"))
        else:
            neutweet += 1
            print(colored("{} {}".format(tweetscore, tweet), "yellow"))
        
if __name__ == "__main__":
    main()
